server:
  port: 8080
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/user
        username: root
        password: Bzm990521
        driver-class-name: com.mysql.jdbc.Driver
    mvc:
        view:
          prefix: /WEB-INF/views
          suffix: .html
mybatis:
    mapper-locations: classpath:mapper/*Mapper.xml
    type-aliases-package: ink.bzm.pojo
